<a href="https://colab.research.google.com/github/anshulsawant/Void-Seg/blob/main/Mask%20R-CNN%20RPN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
### Important: Run this first!!!! ###
from datetime import datetime
print (datetime.now())
private_key = '''-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCudwiyfjV3kuXzc15/a5LDWN48yR4mqaTPU8QgXBdHHwAAAKDwDJ058Ayd
OQAAAAtzc2gtZWQyNTUxOQAAACCudwiyfjV3kuXzc15/a5LDWN48yR4mqaTPU8QgXBdHHw
AAAECLO+NJ+bcV13aI1QFbJsq0N3ncIXyzIvYOsK35P8oJWa53CLJ+NXeS5fNzXn9rksNY
3jzJHiappM9TxCBcF0cfAAAAF2Fuc2h1bC5zYXdhbnRAZ21haWwuY29tAQIDBAUG
-----END OPENSSH PRIVATE KEY-----
'''
!mkdir -p /root/.ssh
with open("/root/.ssh/id_ed25519", "w+") as f:
  f.write(private_key)

!ssh-keyscan -t ed25519 github.com > ~/.ssh/known_hosts
# Restrict the key permissions, or else SSH will complain.
!chmod go-rwx /root/.ssh/id_ed25519
!rm -rf /content/Void-Seg/
!git clone git@github.com:anshulsawant/Void-Seg.git

git_path = '/content/Void-Seg/src'

import sys
if(sys.path.count(git_path) == 0):
  sys.path.append('/content/Void-Seg/src')

import models
import images
import utils
import datasets

import importlib
importlib.reload(models)
importlib.reload(images)
importlib.reload(utils)
importlib.reload(datasets)

2023-01-26 21:38:47.001975
# github.com:22 SSH-2.0-babeld-881dd265
Cloning into 'Void-Seg'...
remote: Enumerating objects: 5036, done.
remote: Counting objects: 100% (202/202), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 5036 (delta 131), reused 194 (delta 128), pack-reused 4834
Receiving objects: 100% (5036/5036), 258.94 MiB | 24.52 MiB/s, done.
Resolving deltas: 100% (2087/2087), done.
Updating files: 100% (5123/5123), done.


<module 'datasets' from '/content/Void-Seg/src/datasets.py'>

In [18]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)
from google.colab import drive

import cv2

from glob import glob
import numpy as np
import os

import keras
import keras.backend as K
import keras.engine as KE
import keras.models as KM
import keras.layers as layers
from IPython.display import clear_output
import matplotlib.pyplot as plt
import matplotlib.patches as patches

import random

from tensorflow.python.ops import math_ops

from skimage import measure

import sys

from datetime import datetime
import os
SIZE = 512

TensorFlow version:  2.9.2


In [3]:
!pip install -U tensorboard_plugin_profile

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 58.7 MB/s eta 0:00:00


In [50]:
K.clear_session()
logs = "logs/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tboard_callback = tf.keras.callbacks.TensorBoard(log_dir = logs)
os.environ['TF_GPU_THREAD_MODE'] = 'gpu_private'
rpn = models.train_rpn(epochs=10, callbacks = [tboard_callback], lr=0.00001)


TypeError: ignored

In [ ]:
x = utils.anchors([512, 512], [32,64,128], [0.5, 1., 2.], 16)
print(x.shape)
utils.clip_anchors(x)


(9216, 4)


<tf.Tensor: shape=(6792, 4), dtype=float32, numpy=
array([[  1.3725834,   4.6862917,  46.62742  ,  27.31371  ],
       [ 17.372583 ,   4.6862917,  62.62742  ,  27.31371  ],
       [ 33.37258  ,   4.6862917,  78.62742  ,  27.31371  ],
       ...,
       [378.74518  , 325.49033  , 469.25482  , 506.50967  ],
       [394.74518  , 325.49033  , 485.25482  , 506.50967  ],
       [410.74518  , 325.49033  , 501.25482  , 506.50967  ]],
      dtype=float32)>

In [ ]:
x = build_rpn_model()
x.summary()
keras.backend.clear_session()

NameError: ignored

In [ ]:
def apply_box_deltas_graph(boxes, deltas):
    """Applies the given deltas to the given boxes.
    boxes: [N, (y1, x1, y2, x2)] boxes to update
    deltas: [N, (dy, dx, log(dh), log(dw))] refinements to apply
    """
    # Convert to y, x, h, w
    height = boxes[:, 2] - boxes[:, 0]
    width = boxes[:, 3] - boxes[:, 1]
    center_y = boxes[:, 0] + 0.5 * height
    center_x = boxes[:, 1] + 0.5 * width
    # Apply deltas
    center_y += deltas[:, 0] * height
    center_x += deltas[:, 1] * width
    height *= tf.exp(deltas[:, 2])
    width *= tf.exp(deltas[:, 3])
    # Convert back to y1, x1, y2, x2
    y1 = center_y - 0.5 * height
    x1 = center_x - 0.5 * width
    y2 = y1 + height
    x2 = x1 + width
    result = tf.stack([y1, x1, y2, x2], axis=1, name="apply_box_deltas_out")
    return result


def clip_boxes_graph(boxes, window):
    """
    boxes: [N, (y1, x1, y2, x2)]
    window: [4] in the form y1, x1, y2, x2
    """
    # Split
    wy1, wx1, wy2, wx2 = tf.split(window, 4)
    y1, x1, y2, x2 = tf.split(boxes, 4, axis=1)
    # Clip
    y1 = tf.maximum(tf.minimum(y1, wy2), wy1)
    x1 = tf.maximum(tf.minimum(x1, wx2), wx1)
    y2 = tf.maximum(tf.minimum(y2, wy2), wy1)
    x2 = tf.maximum(tf.minimum(x2, wx2), wx1)
    clipped = tf.concat([y1, x1, y2, x2], axis=1, name="clipped_boxes")
    clipped.set_shape((clipped.shape[0], 4))
    return clipped
    
class ProposalLayer(KL.Layer):
    """Receives anchor scores and selects a subset to pass as proposals
    to the second stage. Filtering is done based on anchor scores and
    non-max suppression to remove overlaps. It also applies bounding
    box refinement deltas to anchors.
    Inputs:
        rpn_probs: [batch, num_anchors, (bg prob, fg prob)]
        rpn_bbox: [batch, num_anchors, (dy, dx, log(dh), log(dw))]
        anchors: [batch, num_anchors, (y1, x1, y2, x2)] anchors in normalized coordinates
    Returns:
        Proposals in normalized coordinates [batch, rois, (y1, x1, y2, x2)]
    """

    def __init__(self, proposal_count, **kwargs):
        super(ProposalLayer, self).__init__(**kwargs)
        self.proposal_count = proposal_count
        self.nms_threshold = 0.7

    def call(self, inputs):
        batch_size = inputs[0].shape[0]
        # Box Scores. Use the foreground class confidence. [Batch, num_rois, 1]
        scores = inputs[0][:, :, 1]
        # Box deltas [batch, num_rois, 4]
        deltas = inputs[1]
        deltas = deltas * np.reshape(self.config.RPN_BBOX_STD_DEV, [1, 1, 4])
        # Anchors
        anchors = inputs[2]
        # Apply deltas to anchors to get refined anchors.
        # [batch, N, (y1, x1, y2, x2)]

        boxes = batch_slice([anchors, deltas],
                                  lambda x, y: apply_box_deltas_graph(x, y),
                                  batch_size,
                                  names=["refined_anchors"])

        # Clip to image boundaries. Since we're in normalized coordinates,
        # clip to 0..1 range. [batch, N, (y1, x1, y2, x2)]
        window = np.array([0, 0, 1, 1], dtype=np.float32)
        boxes = batch_slice(boxes,
                                  lambda x: clip_boxes_graph(x, window),
                                  batch_size,
                                  names=["refined_anchors_clipped"])

        # Filter out small boxes
        # According to Xinlei Chen's paper, this reduces detection accuracy
        # for small objects, so we're skipping it.

        # Non-max suppression
        def nms(boxes, scores):
            indices = tf.image.non_max_suppression(
                boxes, scores, self.proposal_count,
                self.nms_threshold, name="rpn_non_max_suppression")
            proposals = tf.gather(boxes, indices)
            # Pad if needed
            padding = tf.maximum(self.proposal_count - tf.shape(proposals)[0], 0)
            proposals = tf.pad(proposals, [(0, padding), (0, 0)])
            return proposals
        proposals = batch_slice([boxes, scores], nms, batch_size)
        return proposals

    def compute_output_shape(self, input_shape):
        return (None, self.proposal_count, 4)

In [ ]:
class DetectionTargetLayer(layersLayer):
    """Subsamples proposals and generates target box refinement, class_ids,
    and masks for each.
    Inputs:
    proposals: [batch, N, (y1, x1, y2, x2)] in normalized coordinates. Might
               be zero padded if there are not enough proposals.
    gt_class_ids: [batch, MAX_GT_INSTANCES] Integer class IDs.
    gt_boxes: [batch, MAX_GT_INSTANCES, (y1, x1, y2, x2)] in normalized
              coordinates.
    gt_masks: [batch, height, width, MAX_GT_INSTANCES] of boolean type
    Returns: Target ROIs and corresponding class IDs, bounding box shifts,
    and masks.
    rois: [batch, TRAIN_ROIS_PER_IMAGE, (y1, x1, y2, x2)] in normalized
          coordinates
    target_class_ids: [batch, TRAIN_ROIS_PER_IMAGE]. Integer class IDs.
    target_deltas: [batch, TRAIN_ROIS_PER_IMAGE, (dy, dx, log(dh), log(dw)]
    target_mask: [batch, TRAIN_ROIS_PER_IMAGE, height, width]
                 Masks cropped to bbox boundaries and resized to neural
                 network output size.
    Note: Returned arrays might be zero padded if not enough target ROIs.
    """

    def __init__(self, config, **kwargs):
        super(DetectionTargetLayer, self).__init__(**kwargs)
        self.config = config

    def call(self, inputs):
        proposals = inputs[0]
        gt_class_ids = inputs[1]
        gt_boxes = inputs[2]
        gt_masks = inputs[3]

        # Slice the batch and run a graph for each slice
        # TODO: Rename target_bbox to target_deltas for clarity
        names = ["rois", "target_class_ids", "target_bbox", "target_mask"]
        outputs = utils.batch_slice(
            [proposals, gt_class_ids, gt_boxes, gt_masks],
            lambda w, x, y, z: detection_targets_graph(
                w, x, y, z, self.config),
            self.config.IMAGES_PER_GPU, names=names)
        return outputs

    def compute_output_shape(self, input_shape):
        return [
            (None, self.config.TRAIN_ROIS_PER_IMAGE, 4),  # rois
            (None, self.config.TRAIN_ROIS_PER_IMAGE),  # class_ids
            (None, self.config.TRAIN_ROIS_PER_IMAGE, 4),  # deltas
            (None, self.config.TRAIN_ROIS_PER_IMAGE, self.config.MASK_SHAPE[0],
             self.config.MASK_SHAPE[1])  # masks
        ]

    def compute_mask(self, inputs, mask=None):
        return [None, None, None, None]


In [ ]:
## What does batch_slice do
t = tf.convert_to_tensor(np.random.randn(4, 3))
ix = tf.nn.top_k(t, 2, sorted=True).indices
print(t)
print(ix)
batch_slice([t, ix], lambda x, y: tf.gather(x, y), 2)

tf.Tensor(
[[-0.72178719 -0.12621701  0.17059008]
 [ 0.81531141  0.85252596 -0.21645062]
 [ 0.40437868  0.6521274   0.41926502]
 [ 0.80200095 -1.894487   -1.33180861]], shape=(4, 3), dtype=float64)
tf.Tensor(
[[2 1]
 [1 0]
 [1 2]
 [0 2]], shape=(4, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 0.17059008, -0.12621701],
       [ 0.85252596,  0.81531141]])>

In [ ]:
importlib.reload(images)
images.compute_and_write_bboxes(in_path = '/content/drive/MyDrive/Segmentation/dataset/test')
images.compute_and_write_bboxes(in_path = '/content/drive/MyDrive/Segmentation/dataset/train')
images.compute_and_write_bboxes(in_path = '/content/drive/MyDrive/Segmentation/dataset/holdout')
dataset_path = '/content/drive/MyDrive/Segmentation/dataset'
def name(path):
  return os.path.splitext(os.path.basename(path))[0]

train_images = sorted(glob(os.path.join(dataset_path, 'train', 'images/*.png')))
train_masks = sorted(glob(os.path.join(dataset_path, 'train', 'masks/*.png')))
train_bboxes = sorted(glob(os.path.join(dataset_path, 'train', 'bboxes/*.txt')))
test_images = sorted(glob(os.path.join(dataset_path, 'test', 'images/*.png')))
test_masks = sorted(glob(os.path.join(dataset_path, 'test', 'masks/*.png')))
test_bboxes = sorted(glob(os.path.join(dataset_path, 'test', 'bboxes/*.txt')))
holdout_images = sorted(glob(os.path.join(dataset_path, 'holdout', 'images/*.png')))
holdout_masks = sorted(glob(os.path.join(dataset_path, 'holdout', 'masks/*.png')))
holdout_bboxes = sorted(glob(os.path.join(dataset_path, 'holdout', 'bboxes/*.txt')))

print(len(train_images))
print(len(train_masks))
print(len(train_bboxes))
print(len(test_images))
print(len(test_masks))
print(len(test_bboxes))
print(len(holdout_images))
print(len(holdout_masks))
print(len(holdout_bboxes))
assert(len(train_images) == 1024)
assert(len(test_images) == 32)
assert(len(holdout_images) == 32)

def names(paths):
  return [name(p) for p in paths]

assert(names(train_images) == names(train_masks))
assert(names(train_masks) == names(train_bboxes))
assert(names(test_images) == names(test_masks))
print(test_masks)
print(test_bboxes)
assert(names(test_masks) == names(test_bboxes))
assert(names(holdout_images) == names(holdout_masks))
assert(names(holdout_masks) == names(holdout_bboxes))



/content/drive/MyDrive/Segmentation/dataset/test/masks/100kX_300kV_0636_7_0.png
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0636_7_0.tf
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0636_7_0.txt
/content/drive/MyDrive/Segmentation/dataset/test/masks/100kX_300kV_0651_16_1.png
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0651_16_1.tf
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0651_16_1.txt
/content/drive/MyDrive/Segmentation/dataset/test/masks/100kX_300kV_0651_7_0.png
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0651_7_0.tf
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0651_7_0.txt
/content/drive/MyDrive/Segmentation/dataset/test/masks/100kX_300kV_0537_15_1.png
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0537_15_1.tf
/content/drive/MyDrive/Segmentation/dataset/test/bboxes/100kX_300kV_0537_15_1.txt
/content/drive/MyDrive/Segment

AssertionError: ignored

In [ ]:
images.read_split_augment_and_write_all_images(x, y, out_dir)

/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_0.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_1.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_2.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_3.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_4.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_5.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_6.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_7.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_8.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_9.png
/content/drive/MyDrive/Segmentation/dataset/train/images/100kX_300kV_0537.tiff_1_10.png
/content/drive/MyDrive/Segmentation/datase